config/routes.rb
Rails.application.routes.draw do

  resources :admin_users, :except => [:show]


  get  'admin', :to => 'access#menu' # Redirect to login form if success
  get  'access/menu'
  get  'access/login'
  post 'access/attempt_login'
  get  'access/logout'


  # For the randomizer controller
  get 'randomizer/show'

  # For the subjects resource that has child pages
  resources :subjects do
    member do
      get :delete
    end

    # Each page requires a parent page to be created and viewed
    resources :pages, only: [:index, :new, :create]
  end
  resources :pages, only: [:show, :edit, :update, :destroy]

  # For the pages resource that has child sections
  resources :pages do
    resources :sections, :only => [:index, :new, :create]
  end

  resources :sections, :only => [:show, :edit, :update, :destroy]

  #  Demo controllers
  get 'tests/index'
  get 'tests/welcome'
  get 'tests/escape_output'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/cms', :to => 'subjects#index'
  get '/', :to => redirect('/static_page.html')
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  layout 'admin'

  # before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]
  def menu
    # Display text & links
  end

  def login
    # login form
  end

  def attempt_login
    if params[:email].present? && params[:password].present?
      found_user = AdminUser.where(:email => params[:email]).first
      if(found_user)
        # Returns false or a user object.
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    # Store in session if authorized. Acts as hands-stamp
    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = 'Successfully Logged in'
      redirect_to(admin_path)
    else
      flash.now[:notice] = 'Invalid username/password combo.'
      render('login')
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to access_login_path
  end

  private
    # def confirm_logged_in
    #   unless session[:user_id]
    #     flash[:notice] = "Please login"
    #     redirect_to(access_login_path)
    #   end
    # end
end

app/views/access/login.html.erb
<h1>Access#login</h1>
<p>Find me in app/views/access/login.html.erb</p>

<%= form_tag(access_attempt_login_path) do %>
  <%= label_tag(:email) %>
  <%= text_field_tag(:email, params[:email]) %>
  <%= label_tag(:password) %>
  <%= password_field_tag(:password, params[:password])%>

  <%= submit_tag("Log in") %>
<% end %>

app/views/access/menu.html.erb
<h1>Access#menu</h1>
<p>Find me in app/views/access/menu.html.erb</p>

<%= link_to('Manage Admin Users', admin_users_path) if admin_user %>
<%= link_to('Subjects', subjects_path) %>
<%= link_to('Logout', access_logout_path) %>