config/routes.rb
Rails.application.routes.draw do

  resources :admin_users, :except => [:show]


  get  'admin', :to => 'access#menu' # Redirect to login form if success
  get  'access/menu'
  get  'access/login'
  post 'access/attempt_login'
  get  'access/logout'


  # For the randomizer controller
  get 'randomizer/show'

  # For the subjects resource that has child pages
  resources :subjects do
    member do
      get :delete
    end

    # Each page requires a parent page to be created and viewed
    resources :pages, only: [:index, :new, :create]
  end
  resources :pages, only: [:show, :edit, :update, :destroy]

  # For the pages resource that has child sections
  resources :pages do
    resources :sections, :only => [:index, :new, :create]
  end

  resources :sections, :only => [:show, :edit, :update, :destroy]

  #  Demo controllers
  get 'tests/index'
  get 'tests/welcome'
  get 'tests/escape_output'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/cms', :to => 'subjects#index'
  get '/', :to => redirect('/static_page.html')
end

app/models/section.rb
class Section < ApplicationRecord

  belongs_to :page
  has_many :section_edits

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  layout 'admin'

  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]
  before_action :find_page, :only => [:index, :new, :create]

  def index
    # @page = Page.find(params[:page_id])
    @sections = @page.sections
  end

  def new
    # @page = Page.find(params[:page_id])
    @section = Section.new(:visible => true, :position => 0)
  end

  def create
    # @page = Page.find(create_params[:page_id])
    section = @page.sections.new(create_params[:section])
    if section.save
      flash[:notice] = "Section successfully created!"
      redirect_to page_sections_path(@page)
    else
      flash[:errors] = section.errors.full_messages
      render :new
    end
  rescue Exception => e
    flash[:errors] = e.message
    redirect_to page_sections_path(@page)
  end

  def destroy
    section = Section.find(params[:id])
    if(section.destroy)
      flash[:notice] = 'Section succesfully destroyed!'
      redirect_to page_sections_path(section.page.id)
    else
      flash[:errors] = section.errors.full_messages
      redirect_to page_sections_path(section.page.id)
    end
  rescue ActiveRecord::RecordNotFound => e
    flash[:errors] = 'Cannot find this section'
    redirect_to :back
  rescue Exception => e
    flash[:errors] = e.message
    redirect_to page_sections_path(section.page.id)
  end

  private
    def create_params
      params.permit(:page_id, :section => [:name, :position, :visible, :content, :content_type])
    end

    def find_page
      @page = Page.find(params[:page_id])
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/edit.html.erb
<h1>Sections#edit</h1>
<p>Find me in app/views/sections/edit.html.erb</p>

app/views/sections/index.html.erb
<%= link_to('<< Back to Subject', subject_path(@page.subject_id)) %>

<h1> Sections for <%= @page.name %> </h1>
<div class="col-md-3"><%=link_to('Add Section', new_page_section_path(:page_id => @page.id))%></div>
<hr/>
<% @sections.each do |s| %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <label>Name:</label>
      <%= s.name %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <label>Position:</label>
      <%= s.position %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">

      <label>Visible:</label>
      <%= s.visible.to_s.capitalize %>
    </div>
    <div class="col-md-3">
      <label>Created:
      </label>
      <%= s.created_at.to_formatted_s(:long_ordinal) %>
    </div>
    <div class="col-md-3">
      <label>Updated:
      </label>
      <%= s.updated_at.to_formatted_s(:long_ordinal) %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2"><label>Actions:</label></div>
    <div class="col-md-3"><%=button_to('Delete section', {:controller => :sections, :action => :destroy, :id => s.id}, {:method => :delete, :onclick => "return confirm('Are you sure?')" } )%></div>
  </div>
</div>

<hr/>


<% end %>

app/views/sections/new.html.erb
<h1> Create a new Section for <%=@page.name%></h1>

<%= form_for(@section, :url => page_sections_path) do |f| %>
  <div class="form-group">
    <%= f.label(:name) %>
    <%= f.text_field(:name, :class=> "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label(:content_type) %>
    <%= f.text_field(:content_type, :class=> "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label(:content) %>
    <%= f.text_area(:content, :class=> "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label(:position) %>
    <%= f.number_field(:position, :min => 0, :class=> "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label(:visible) %>
    <%= f.check_box(:visible, :class=> "form-control") %>
  </div>

<!-- Position, Visible, Content Type, Content  -->

  <div class="form-group">
    <%= f.submit('Create Section', {:class=>"btn btn-primary"}) %>
  </div>
<% end %>

<div class="form-group">
  <%= button_tag('Randomize!', :type => :button, :class=>"btn btn-primary", :onClick=>'randomize_section()') %>
</div>

app/views/sections/show.html.erb
<h1>Sections#show</h1>
<p>Find me in app/views/sections/show.html.erb</p>