config/routes.rb
Rails.application.routes.draw do

  resources :admin_users, :except => [:show]


  get  'admin', :to => 'access#menu' # Redirect to login form if success
  get  'access/menu'
  get  'access/login'
  post 'access/attempt_login'
  get  'access/logout'


  # For the randomizer controller
  get 'randomizer/show'

  # For the subjects resource that has child pages
  resources :subjects do
    member do
      get :delete
    end

    # Each page requires a parent page to be created and viewed
    resources :pages, only: [:index, :new, :create]
  end
  resources :pages, only: [:show, :edit, :update, :destroy]

  # For the pages resource that has child sections
  resources :pages do
    resources :sections, :only => [:index, :new, :create]
  end

  resources :sections, :only => [:show, :edit, :update, :destroy]

  #  Demo controllers
  get 'tests/index'
  get 'tests/welcome'
  get 'tests/escape_output'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/cms', :to => 'subjects#index'
  get '/', :to => redirect('/static_page.html')
end

app/views/pages/_show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <label>Name:</label>
      <%= page.name %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <label>Position:</label>
      <%= page.position %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">

      <label>Visible:</label>
      <%= page.visible.to_s.capitalize %>
    </div>
    <div class="col-md-3">
      <label>Created:
      </label>
      <%= page.subject.created_at.to_formatted_s(:long_ordinal) %>
    </div>
    <div class="col-md-3">
      <label>Updated:
      </label>
      <%= page.updated_at.to_formatted_s(:long_ordinal) %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2"><label>Actions:</label></div>
    <div class="col-md-3"><%=button_to('Delete Page', {:controller => :pages, :action => :destroy, :subject_id => page.subject_id, :id => page.id}, {:method => :delete, :onclick => "return confirm('Are you sure?')" } )%></div>
    <div class="col-md-3"><%=link_to('Add Section', new_page_section_path(:page_id => page.id))%></div>
    <div class="col-md-3"><%= show_sections(page) %></div>
  </div>
</div>
<hr/>

app/views/pages/index.html.erb
<h1> Pages </h1>

<%= render partial: 'pages/show', collection: @pages, :as => :page %>

app/views/pages/new.html.erb
<%= link_to('<< Back to Subjects', subjects_path) %>
<h1> New Page for <%= @subject.name %> </h1>
<hr/>

<table>
<%= form_for(@page, :url => subject_pages_path(@subject)) do |f| %>
<tr>
  <td><label>Name</label> </td>
  <td><%= f.text_field(:name, :size => 100)%> </td>
</tr>
<tr>
  <td><label>Position</label> </td>
  <td><%= f.number_field(:position, :min => 1)%> </td>
</tr>
<tr>
  <td><label>Visible</label> </td>
  <td><%= f.check_box(:visible)%> </td>
</tr>
<tr>
  <td><label>Permalink</label> </td>
  <td><%= f.label(:permalink, :value => rand(10000..99999), :disabled => true)%> </td>
</tr>
<tr>
  <td> <%= f.submit %> </td>
  <% end %>
  <td> <%= button_to('Cancel', {:controller => :subjects, :action => :index}, {:method => :get}) %> </td>
</tr>
<tr>
  <td> <%= button_tag('Randomize!', :type=> :button, :onClick => 'randomize_page()' )%> </td>
</tr>
</table>