config/routes.rb
Rails.application.routes.draw do

  resources :admin_users, :except => [:show]


  get  'admin', :to => 'access#menu' # Redirect to login form if success
  get  'access/menu'
  get  'access/login'
  post 'access/attempt_login'
  get  'access/logout'


  # For the randomizer controller
  get 'randomizer/show'

  # For the subjects resource that has child pages
  resources :subjects do
    member do
      get :delete
    end

    # Each page requires a parent page to be created and viewed
    resources :pages, only: [:index, :new, :create]
  end
  resources :pages, only: [:show, :edit, :update, :destroy]

  # For the pages resource that has child sections
  resources :pages do
    resources :sections, :only => [:index, :new, :create]
  end

  resources :sections, :only => [:show, :edit, :update, :destroy]

  #  Demo controllers
  get 'tests/index'
  get 'tests/welcome'
  get 'tests/escape_output'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/cms', :to => 'subjects#index'
  get '/', :to => redirect('/static_page.html')
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :pages, :dependent => :destroy

  scope :sorted, lambda{ order(:position=> 'ASC')}
  scope :visible, lambda{ where(:visible => true)}
  scope :search, lambda{ |term| where('name RLIKE ?', "#{term}") }

  validates :name, :presence => true
  validates :visible, :inclusion => {:in => [true, false] }
  validates :position, :presence => true, :numericality => { :greater_than_or_equal_to => 0}
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  layout 'admin'

  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]

  def index
    @subjects = Subject.sorted
    @page_title = 'All Subjects'
  end

  def show
    @subject = Subject.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :plain => 'Record not found'
  end

  def new
    @subject = Subject.new(:visible => true)
  end

  def create
    @subject = Subject.create(create_params)
    if(@subject.save)
      flash[:notice] = 'Subject created successfully'
      redirect_to subjects_path
    else
      flash[:error] = @subject.errors
      render :new
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    render :plain => 'Subject not found!'
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update_attributes(create_params)
      flash[:notice] = 'Subject updated successfully'
      redirect_to subject_path(@subject)
    else
      flash[:errors] = @subject.errors
      render :edit
    end
  rescue ActiveRecord::RecordNotFound => e
    flash[:errors] = 'Not found'
    redirect_to subjects_path
  rescue Exception => e
    flash[:errors] = 'PROBLEM WITH UPDATE'
    redirect_to subjects_path
  end

  def delete
    @subject = Subject.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:errors] = 'Record Not Found'
    redirect_to subjects_path
  end

  def destroy
    @subject = Subject.find(params[:id])
    if @subject.destroy
      flash[:notice] = "Subject '#{@subject.name} destroyed successfully"
      redirect_to(subjects_path)
    else
      flash[:errors] = @subject.errors
      render :delete
    end
  rescue ActiveRecord::RecordNotFound => e
    flash[:errors] = 'Rec not found'
    redirect_to(subjects_path)
  rescue Exception => e
    flash[:errors] = e.message
    render :delete
  end

  private
    def create_params
      params.require(:subject).permit(:name, :position, :visible)
    end
end

app/views/subjects/delete.html.erb
<h1> Are you sure? </h1>
<% unless flash[:errors].blank? %>
<h2><%=flash[:errors].inspect %></h2>
<% end %>
<%= form_for(@subject, :url => subject_path(@subject), :method => :delete) do |f|%>
  <table>
    <tr>
      <td><strong><%= f.label(:name) %></strong></td>
      <td><%= f.object.name %></td>
    </tr>
    <tr>
      <td><strong><%= f.label(:position) %></strong></td>
      <td><%= f.object.position %></td>
    </tr>
    <tr>
      <td><strong><%= f.label(:visible) %></strong></td>
      <td><%= f.object.visible %></td>
    </tr>
    <tr>
      <td><%= f.submit('Yes') %></td>
      <% end %>

      <!-- Cancel button needs to be outside of the submit form, so it doesn't
            bind to the wrong controller action  -->
      <td><%= button_to('No', {:action => :index}, {:method => :get}) %> </td>
    </tr>
  </table>

app/views/subjects/edit.html.erb
<h1> Edit Subject </h1>

<table summary="Subject form fields">
  <%= form_for(@subject) do |f| %>

  <tr>
    <td><label>Name</label> </td>
    <td><%= f.text_field(:name)%> </td>
  </tr>

  <tr>
    <td><label>Position</label> </td>
    <td><%= f.text_field(:position)%> </td>
  </tr>

  <tr>
    <td><label>Visible</label>
    <td><%= f.select(:visible, [true, false])%> </td>
  </tr>

  <tr>
    <td> <%= f.submit('Update subject') %> </td>
  </tr>

  <% end %>
</table>

app/views/subjects/index.html.erb
<h1> Displaying Subject </h1>
<%= link_to('Add New Subject', new_subject_path) %>
<hr>

<table border='1'>
  <tr>
    <th>#</th>
    <th>Subject</th>
    <th>Visible</th>
    <th>Pages</th>
    <th>Actions</th>
  </tr>
  <% @subjects.each do |subject| %>
  <tr>
    <td> <%= subject.position %> </td>
    <td> <%= subject.name %> </td>
    <td> <%= status_tag(subject.visible?) %></td>
    <td> <%= subject.pages.count %> </td>
    <td>
      <%=link_to('Show', subject_path(subject)) %>
      <%=link_to('Edit', edit_subject_path(subject)) %>
      <%=link_to('Delete', delete_subject_path(subject)) %>
      <%=link_to('Add Pages', new_subject_page_path(subject) ) %>
    </td>
  </tr>
  <% end %>
</table>

<hr/>

Test button
<%= button_tag 'I am a button', :type => :button, :onClick => 'subject_index_js_function()' %>

app/views/subjects/new.html.erb
<%= link_to('<< Back to Subjects', subjects_path) %>
<h1> New Subject </h1>

<td> <%= button_tag('Randomize!', :type=> :button, :onClick => 'randomize_subject()' ) %> </td>
<table summary="Subject form fields">
  <%= form_for(@subject) do |f| %>
  <%= error_messages_for(f.object) %>

  <tr>
    <td><label>Name</label> </td>
    <td><%= f.text_field(:name, :size => 100)%> </td>
  </tr>

  <tr>
    <td><label>Position</label> </td>
    <td><%= f.number_field(:position, :min => 0)%> </td>
  </tr>

  <tr>
    <td><label>Visible</label>
    <td><%= f.select(:visible, [true, false])%> </td>
  </tr>

  <tr>
    <td> <%= f.submit('Create new subject') %> </td>
    <% end %>
    <td> <%= button_to('Cancel', {:action => :index}, {:method => :get}) %> </td>
  </tr>
</table>

app/views/subjects/show.html.erb
<br/>
<%= link_to('<< Back to List', subjects_path) %>
<hr/>
<h1> Subject Info </h1>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <label>Subject:</label>
      <%= @subject.name %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <label>Position:</label>
      <%= @subject.position %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">

      <label>Visible:</label>
      <%= @subject.visible %>
    </div>
    <div class="col-md-3">
      <label>Created:
      </label>
      <%= @subject.created_at.to_formatted_s(:long_ordinal) %>
    </div>
    <div class="col-md-3">
      <label>Updated:
      </label>
      <%= @subject.updated_at.to_formatted_s(:long_ordinal) %>
    </div>
  </div>
</div>

<hr/>

<h1> Available Pages </h1>
<%= render partial: 'pages/show', collection: @subject.pages, :as => :page || "No pages to display" %>